/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package analizadorlexico;

public enum Token {

ERROR,ERROR_UNTERM_STRING,ERROR_UNTERM_COMMENT,XML_LANGUAGE,XMLNS,XML_SPACE,XMLNS_XSI,HTTP_EQUIVALENT,TITLE,LANGUAGE,CONTENT,OPTION,SELECT,SELECTED,META_DECLARATION,VERSION,ENCODING, NOT, YY ,OO, IGUALIGUAL, DIFERENTE,MAYORIGUAL,MENORIGUAL,MENOSNUM, MENOSUNO, MASNUM, MASUNO, MAS, PORNUM, ENTRENUM, MENOS, POR, RESIDUO, EQUALS, SEMICOLON, COMA, LPAR, RPAR, LCBRACE, RCBRACE,
DOCUMENT_EXTERNALSOURCE_LINK, STYLE,DEFAULT_ADDRESS,META_DATA,SCRIPT,DOCTYPE,BODY,BREAK,HORIZONTAL_RULE,IMAGE,SOURCE,ALTERNATIVE_NAME, PARRAGRAPH,TABLE,TABLE_ROW,TABLE_ITEM,UNORDERED_LIST,ORDERED_LIST,DEFINITION_LIST,
DEFINITION_LIST_ITEM, DEFINITION_LIST_DESCRIPTION,BLOCK_LEVEL_SECTION,BLOCK_LEVEL_INLINE,FORM,INPUT,TYPE,NAME,VALUE,INPUT_ACTION,INPUT_METHOD,IFRAME,IFRAME_FRAMEBORDER,IFRAME_TARGET_LINK,WIDTH,HEIGHT,REFERENCE,LINK, BOLD_FORMATTING,
ITALIC_FORMATTING,TEXT,HEADING,ID, NUMBER, LIST_ITEM, CLOSE_DECLARATION, HTML, START_TAG, CLOSE_TAG, END_TAG , HEAD, STRING,XML,ADDRESS,SUMMARY,CAPTION,COLUMN,TABLE_HEADER,SCOPE,TABLE_HEAD,TABLE_FOOT,TABLE_BODY
}
